### ISSUE TITLE
Creating Widgets to Integrate with the Backend

### ISSUE THREAD

**Issue by MerrittMelker** [Sitefinity/feather#1939]
Are there embedded stylesheets for kendo and the sitefinity backend I can use and how do I go about interacting with them?
Are these embedded?
```
    <link rel="stylesheet" href="styles/kendo.common.min.css" />
    <link rel="stylesheet" href="styles/kendo.default.min.css" />
```

Also, what is the proper way to integrate the loading placeholders I see in the backend, usually appearing as so?

```
<div style="display: none;" class="RadAjax"><div class="raDiv">Loading...</div><div class="raColor"></div></div>
```

I notice they have "brother" classes:

```
.sfHasMultiSite div.RadAjax,.sfHasMultiSite .k-loading-mask{top:121px!important}
div.RadAjax,.k-loading-mask{position:absolute!important;width:100%!important;height:37px!important;left:0!important;top:90px!important;text-align:left!important;z-index:2900!important;border-top:1px solid #fff;border-bottom:1px solid #ccc;background-color:#DEE2E7!important;color:#105ab5!important}
div.RadAjax div.raDiv,.k-loading-mask .k-loading-text{display:-moz-inline-stack;display:inline-block;zoom:1;*display:inline;width:auto;height:auto;min-height:23px;min-width:16px;margin-top:6px;margin-left:45px;padding-left:30px;font-size:14px;background:transparent url(/WebResource.axd?d=lpbicFwLLRcBsAQ0J5MCIPEGyRcxFTQq1w-11a1zXCD0flt20Jw0MCP0haGTGkbAt64af7Te4zT3LG-t_F1lDpLIBPU07FIlXtN9y4XvrrRjFuHT9RfjS2evPj1pY-yez1252zX-8QUdnC2WDsHAUzr9vhiUx1PGwCCl9L_yrUybXj0Ljx9jg-wBjhVjBgdjMbkr2NU2xk2Hx0kbiKykfPlLKuMAmnlVmEfokYyTMh81&t=635675707920059829) no-repeat 0 1px;font-weight:bold}
```
But I am not sure exactly how to leverage them because there's some sort of system compiling all the stylesheets and returning them using Telerik.Web.UI.WebResource.axd

**Comment by ElenaGaneva** [comment]
Hello Merritt,

You can refer some of the kendo styles directly from Sitefinity like this:
@Html.StyleSheet(Url.EmbeddedResource("Telerik.Sitefinity.Resources.Reference", "Telerik.Sitefinity.Resources.Scripts.Kendo.styles.kendo_common_min.css"), "head")
@Html.StyleSheet(Url.EmbeddedResource("Telerik.Sitefinity.Resources.Reference", "Telerik.Sitefinity.Resources.Scripts.Kendo.styles.kendo_default_min.css"), "head")
@Html.StyleSheet(Url.EmbeddedResource("Telerik.Sitefinity.Resources.Reference", "Telerik.Sitefinity.Resources.Scripts.Kendo.styles.kendo_metro_min.css"), "head")
@Html.StyleSheet(Url.EmbeddedResource("Telerik.Sitefinity.Resources.Reference", "Telerik.Sitefinity.Resources.Scripts.Kendo.styles.kendo_mobile_all_min.css"), "head")

This way in case you are having hybrid page and you are using some of the WebForms Sitefinity widgets these scripts won’t be loaded more than once. 

For your second question- the mentioned loading indicator was used from the WebForms controls in Sitefinity. In Feather you can have full control over your markup in case you are using pure MVC page template (like Bootstrap). In this case we provide loading indicator that could be used with the following markup:
<div class="sf-loading"><span></span></div>  

And the styles are loaded like this:
@Html.StyleSheet(Url.WidgetContent("~/ResourcePackages/Bootstrap/assets/dist/css/styles.min.css"), "head")

If you need any additional assistance on this matter please feel free to ask.

Regards,
Elena

**Comment by MerrittMelker** [comment]
Most of this works great, thanks, unfortunately the bootstrap style seems to break some of the existing style of your backend pages, something I noticed when i was using a cdn version.

So adding:
```html
@Html.StyleSheet(Url.WidgetContent("~/ResourcePackages/Bootstrap/assets/dist/css/styles.min.css"), "head")
```
Gives you this: 

![testing tools after](https://cloud.githubusercontent.com/assets/11414229/7991843/c99aa918-0ac0-11e5-865e-5bdbb325885d.png)

Removing that stylesheet, but including the rest, you get:

![testing tools before](https://cloud.githubusercontent.com/assets/11414229/7991854/e38a079c-0ac0-11e5-8731-e2d887e66039.png)

**Comment by ElenaGaneva** [comment]
Hi Merritt,

Actually we recommend the styles.min.css for the frontend widgets:

````
@Html.StyleSheet(Url.WidgetContent("~/ResourcePackages/Bootstrap/assets/dist/css/styles.min.css"), "head")

````

In case you want to display loading on the backend I suggest you try the following:

````
<div class="RadAjax"><div class="raDiv">Loading...</div><div class="raColor"></div></div>

````

And load the stylesheet:

````

@Html.StyleSheet(Url.EmbeddedResource("Telerik.Sitefinity.Resources.Reference", "Telerik.Sitefinity.Resources.Themes.Default.Styles.Ajax.css"), "head")

````

Regards,
Elena

**Comment by MerrittMelker** [comment]
Thanks for the feedback: I opted for creating my own style based on sf-loading:

```html
<div id="progressBar" class="myloader" style="display: none">Please Wait...</div>
```

````css
.myloader {
    background-attachment: scroll;
    background-clip: border-box;
    background-color: transparent;
    background-image: url("/Mvc/Images/WebResource.axd.gif");
    background-origin: padding-box;
    background-position: 0px 1px;
    background-repeat: no-repeat;
    background-size: auto auto;
    color: #105AB5;
    display: inline-block;
    font-family: Arial, Verdana, sans-serif;
    font-size: 14px;
    font-weight: 700;
    height: 23px;
    line-height: 21px;
    margin-bottom: 0px;
    margin-left: 45px;
    margin-right: 0px;
    margin-top: 6px;
    min-height: 23px;
    min-width: 16px;
    padding-bottom: 0px;
    padding-left: 30px;
    padding-right: 0px;
    padding-top: 0px;
}
```
